### ISSUE TITLE
vue后台获取的数据作为饼状图中的data的value值

### ISSUE THREAD

**Issue by RookiEzz** [lin-xin/vue-schart#1]
进入页面就进行图表渲染了，没有回调去设置这个值吗？我获取到的值还来不及写进去canvas就出来了

**Comment by lin-xin** [comment]
@RookiEzz 你好，这确实是个bug，我已经发了个新的版本，可以更新一下试试。

**Comment by zhangwenwu** [comment]
还是这个问题，我该怎么重新进行图表渲染~发布了新的版本是重新npm install vue-schart吗~~

**Comment by zhangwenwu** [comment]
@lin-xin

**Comment by lin-xin** [comment]
是啊，你本地的版本是什么时候的？ @zhangwenwu

**Comment by zhangwenwu** [comment]
@lin-xin 前几天的，应该是新的了，怎么重新进行图表渲染啊~~

**Comment by lin-xin** [comment]
会监听数据变化就会重新渲染啊。 @zhangwenwu

**Comment by zhangwenwu** [comment]
@lin-xin 并不会啊。https://github.com/lin-xin/vue-schart，我是直接复制你这个页面的代码拿来用的，数据改变了就没渲染，我不知道是要加什么东西上去啊，原谅小白~~~

**Comment by lin-xin** [comment]
@zhangwenwu 不知道你的数据是如何改变的。请参考一下 http://blog.gdfengshuo.com/2017/06/17/16
里的数据响应，这是改变数据的例子。

**Comment by zhangwenwu** [comment]
@lin-xin  解决了，谢谢，this.$set(this.data);就可以了
