### ISSUE TITLE
type ring not working

### ISSUE THREAD

**Issue by apooslr** [lin-xin/vue-schart#2]
I am trying to make a 'ring' chart following you example from:
http://blog.gdfengshuo.com/example/#/vue-schart

Following this example I can make a 'line','bar' and 'pie' chart, but when I change the type to 'ring' I a 'pie' chart is still rendered. I am using the same code as in the example. How do I make a 'ring' chart work??

**Comment by lin-xin** [comment]
![image](https://user-images.githubusercontent.com/13494930/30417250-a5f20b96-9961-11e7-9c64-29edd65fd26a.png)

Is it like this?

**Comment by apooslr** [comment]
Yes, that is what I want , but dont get

**Comment by lin-xin** [comment]
Is there any error thrown in the browser console?

**Comment by apooslr** [comment]
No there is no error in the browser console

**Comment by lin-xin** [comment]
That's strange. In my Google browser, it's normal rendering. Can you try another browser?

**Comment by apooslr** [comment]
I tried safari as well, same result

**Comment by apooslr** [comment]
![image](https://user-images.githubusercontent.com/5477452/30418657-fed7c4b8-9933-11e7-9d89-e2813215e8ba.png)

**Comment by apooslr** [comment]
The above code give me this chart:

![image](https://user-images.githubusercontent.com/5477452/30418711-372830d2-9934-11e7-8f2f-c35695b07d14.png)
