### ISSUE TITLE
设置宽高无效，F12查看和官网demo生成的元素不一致。

### ISSUE THREAD

**Issue by shen-lan** [lin-xin/vue-schart#8]
1.代码：环形图。直接官网拷贝下来的。`http://blog.gdfengshuo.com/example/#/vue-schart`
2.问题：设置宽高无效，cavans元素会是100%宽度，不按设置的来。
3.F12查看和官网对比，有差距。
4.我的元素。【注：Device元素50%宽度，没有设置高度】
`<div id="Devide"><div width="500" height="400"><canvas id="myCanvas1" width="684" height="170" style="width:622px;height:175px;"></canvas></div></div>`
5.官网demo元素
`<div data-v-4aaf78af="" class="center ivu-col ivu-col-span-24"><div data-v-4aaf78af=""><canvas id="mycanvas" width="500" height="400"></canvas></div></div>`

**Comment by hotlt** [comment]
确实，严重bug，没法用啊

**Comment by hotlt** [comment]
vue-schart 文件里没写宽度和和高度的props，自己写一个组件加上即可。作者粗心了。

**Comment by lin-xin** [comment]
@hotlt V1.0.0版本不再使用props设置宽高，而是添加class去设置宽高来支持rem,%等单位，具体使用方法请看 https://github.com/lin-xin/vue-schart/blob/master/README.md
